/* =============================================================================
   Anachrony — Components glossary data (standard v1.1; rendered by js/comp-widget.js)
   Sources (component lists): Essential Edition rulebook p.2–3 · Classic Expansion Pack p.2 · Fractures of Time
   p.2–3 · Future Imperfect p.2–3 · Solo Opponents (Chronobot & Chronossus) p.2–3. Pictures cropped from those pages.
   Gating: module components show only with their module (Classic p.2, Future Imperfect p.2–3, Fractures p.3).
   Replacements hidden: base Anomaly tiles with Variable Anomalies (Fractures p.13); base Scoring pad with Fractures of
   Time (Fractures p.12); every Endgame Condition card with Intrigues of the Council (Future Imperfect p.8–9) and in
   solo play (Solo p.4, p.8). Starting Asset cards appear only with the Starting Asset Draft variant (Essential p.20,
   Fractures p.15). Solo components appear at 1 player; Chronossus-only ones with the Chronossus (Solo p.2–3).
   Classic p.2 prints the Doomsday and Pioneers Endgame Condition card pictures under each other's heading; the two
   pictures are swapped here to match the cards themselves (Classic p.3 figure, p.15 appendix).
   ============================================================================= */
window.AID_COMPONENTS = {
  sets: [
    { id: "base", name: "Essential Edition", src: "Essential p.2–3" },
    { id: "classic", name: "Classic Expansion Pack", src: "Classic p.2", when: (c) => c.has("classic") },
    { id: "fot", name: "Fractures of Time", src: "Fractures p.2–3", when: (c) => c.has("fot") },
    { id: "fi", name: "Future Imperfect", src: "Future Imperfect p.2–3", when: (c) => c.has("fi") },
    { id: "solo", name: "Solo Opponents: Chronobot & Chronossus", src: "Solo p.2–3", when: (c) => c.p === 1 }
  ],
  items: [
    { set: "base", qty: "1", name: "Main board", img: "base-main-board.webp", w: 320, h: 213 },
    { set: "base", qty: "4×1", name: "Dual-sided Path boards", img: "base-path-boards.webp", w: 320, h: 308 },
    { set: "base", qty: "4×1", name: "Player boards", img: "base-player-boards.webp", w: 320, h: 138 },
    { set: "base", qty: "4×2", name: "Leader cards", img: "base-leader-cards.webp", w: 320, h: 168 },
    { set: "base", qty: "25", name: "Scientist", note: "Worker. Supply not limited (Essential p.2)", img: "base-scientist.webp", w: 98, h: 135 },
    { set: "base", qty: "25", name: "Engineer", note: "Worker. Supply not limited (Essential p.2)", img: "base-engineer.webp", w: 93, h: 135 },
    { set: "base", qty: "15", name: "Administrator", note: "Worker. Supply not limited (Essential p.2)", img: "base-administrator.webp", w: 93, h: 135 },
    { set: "base", qty: "15", name: "Genius", note: "Worker. Supply not limited (Essential p.2)", img: "base-genius.webp", w: 98, h: 135 },
    { set: "base", name: "Resources (cubes)", note: "15 Neutronium (purple), 20 Gold (yellow), 20 Uranium (green), 25 Titanium (grey). Supply not limited (Essential p.2)", img: "base-resources.webp", w: 145, h: 154 },
    { set: "base", qty: "24", name: "Energy Core tokens", img: "base-energy-cores.webp", w: 276, h: 145 },
    { set: "base", qty: "66", name: "Victory Point tokens", note: "30 × 5 VPs, 35 × 1 VPs and 1 × −3 VPs", img: "base-vp-tokens.webp", w: 320, h: 126 },
    { set: "base", name: "Water", note: "24 “1 Water” drops (light blue) and 6 “5 Water” drops (dark blue). Supply not limited (Essential p.2)", img: "base-water.webp", w: 278, h: 214 },
    { set: "base", qty: "4×1", name: "Player banners with plastic standee", img: "base-banners.webp", w: 320, h: 217 },
    { set: "base", qty: "4×1", name: "Dual-sided player aid cards", img: "base-player-aids.webp", w: 280, h: 275 },
    { set: "base", qty: "4×6", name: "Hex-shaped Exosuit markers", img: "base-exosuit-markers.webp", w: 279, h: 295 },
    { set: "base", qty: "4×2", name: "Time Travel and Morale markers", note: "Plus 1 spare of each", img: "base-tt-morale-markers.webp", w: 227, h: 162 },
    { set: "base", qty: "4×8", name: "Path markers", img: "base-path-markers.webp", w: 223, h: 167 },
    { set: "base", qty: "4×9", name: "Warp tiles", note: "3 Workers, 4 Resources, 1 “2 Water” and 1 powered up Exosuit per Path", img: "base-warp-tiles.webp", w: 195, h: 173 },
    { set: "base", qty: "4×15", name: "Building tiles", note: "Power Plants, Factories, Life Supports and Labs", img: "base-buildings.webp", w: 320, h: 140 },
    { set: "base", qty: "11", name: "Recruit pool cards", img: "base-recruit-cards.webp", w: 141, h: 212 },
    { set: "base", qty: "11", name: "Mine pool cards", img: "base-mine-cards.webp", w: 136, h: 212 },
    { set: "base", qty: "9", name: "Dual-sided Timeline tiles", img: "base-timeline-tiles.webp", w: 320, h: 230 },
    { set: "base", qty: "1", name: "Impact tile", img: "base-impact-tile.webp", w: 206, h: 154 },
    { set: "base", qty: "18", name: "Superproject tiles", img: "base-superprojects.webp", w: 320, h: 197 },
    { set: "base", qty: "2", name: "Research dice", img: "base-research-dice.webp", w: 308, h: 173 },
    { set: "base", qty: "1", name: "Paradox die", img: "base-paradox-die.webp", w: 152, h: 162 },
    { set: "base", qty: "1", name: "Dual-sided Evacuation Action tile", img: "base-evacuation-tile.webp", w: 320, h: 175 },
    { set: "base", qty: "12", name: "Anomaly tiles", img: "base-anomalies.webp", w: 213, h: 242, when: (c) => !c.mod("vanom") },
    { set: "base", qty: "3×15", name: "Breakthrough tiles", img: "base-breakthroughs.webp", w: 294, h: 200 },
    { set: "base", qty: "15", name: "Collapsing Capital tiles", img: "base-collapsing-capital.webp", w: 320, h: 207 },
    { set: "base", qty: "9", name: "“Hex Unavailable” tiles", img: "base-hex-unavailable.webp", w: 280, h: 224 },
    { set: "base", qty: "8", name: "Endgame Condition cards", img: "base-endgame-cards.webp", w: 318, h: 248, when: (c) => c.p !== 1 && !c.mod("ic") },
    { set: "base", qty: "16", name: "Starting Asset cards", note: "Used in the Starting Asset Draft variant (Essential p.20)", img: "base-starting-assets.webp", w: 320, h: 228, when: (c) => c.mod("draft") },
    { set: "base", qty: "1", name: "Scoring pad", img: "base-scoring-pad.webp", w: 207, h: 285, when: (c) => !c.has("fot") },
    { set: "base", qty: "16", name: "Paradox tokens", img: "base-paradox-tokens.webp", w: 179, h: 198 },
    { set: "classic", qty: "1", name: "Doomsday board", img: "classic-doomsday-board.webp", w: 142, h: 320, when: (c) => c.mod("doomsday") },
    { set: "classic", qty: "10", name: "Level 1 Experiments", img: "classic-experiments.webp", w: 320, h: 188, when: (c) => c.mod("doomsday") },
    { set: "classic", qty: "10", name: "Level 2 Experiments", img: "classic-experiments.webp", w: 320, h: 188, when: (c) => c.mod("doomsday") },
    { set: "classic", qty: "1", name: "Endgame Condition card", note: "Doomsday: “Most Completed Experiments” (Classic p.3)", img: "classic-doomsday-endgame.webp", w: 170, h: 225, when: (c) => c.mod("doomsday") && c.p !== 1 && !c.mod("ic") },
    { set: "classic", qty: "2", name: "Trajectory dice", img: "classic-trajectory-dice.webp", w: 187, h: 126, when: (c) => c.mod("doomsday") },
    { set: "classic", qty: "1", name: "“Save Earth” Tracker token", note: "Plus 1 spare. The pale blue token; the orange one is Seal Fate (Classic p.3)", img: "classic-trackers.webp", w: 140, h: 203, when: (c) => c.mod("doomsday") },
    { set: "classic", qty: "1", name: "“Seal Fate” Tracker token", note: "Plus 1 spare. The orange starburst token (Classic p.3)", img: "classic-trackers.webp", w: 140, h: 203, when: (c) => c.mod("doomsday") },
    { set: "classic", qty: "10", name: "Level 2 Experiments (Doomsday Enhancement Pack)", note: "Setup shuffles all Level 2 Experiments into one stack (Classic p.3)", img: "classic-enh-experiments.webp", w: 317, h: 195, when: (c) => c.mod("doomsday") },
    { set: "classic", qty: "1", name: "Adventure board", img: "classic-adventure-board.webp", w: 139, h: 320, when: (c) => c.mod("pioneers") },
    { set: "classic", qty: "18", name: "Adventure cards (5+)", img: "classic-adventure-5.webp", w: 320, h: 291, when: (c) => c.mod("pioneers") },
    { set: "classic", qty: "18", name: "Adventure cards (10+)", img: "classic-adventure-10.webp", w: 320, h: 283, when: (c) => c.mod("pioneers") },
    { set: "classic", qty: "4", name: "Exosuit Upgrade boards", img: "classic-exosuit-upgrades.webp", w: 320, h: 229, when: (c) => c.mod("pioneers") },
    { set: "classic", qty: "1", name: "Adventure reference card", img: "classic-adventure-ref.webp", w: 217, h: 299, when: (c) => c.mod("pioneers") },
    { set: "classic", qty: "1", name: "Endgame Condition card", note: "Pioneers: “Most Successful Adventures” (Classic p.6)", img: "classic-pioneers-endgame.webp", w: 153, h: 247, when: (c) => c.mod("pioneers") && c.p !== 1 && !c.mod("ic") },
    { set: "classic", qty: "1", name: "Adventure die", img: "classic-adventure-die.webp", w: 106, h: 117, when: (c) => c.mod("pioneers") },
    { set: "classic", qty: "1", name: "Guardian board", img: "classic-guardian-board.webp", w: 320, h: 151, when: (c) => c.mod("guardians") },
    { set: "classic", qty: "6", name: "Hex-shaped Exosuit markers", note: "Guardian Exosuits: use these or the miniatures (Classic p.9)", img: "classic-guardian-markers.webp", w: 155, h: 203, when: (c) => c.mod("guardians") },
    { set: "classic", qty: "6", name: "Guardian miniatures", note: "May be used instead of the Guardian Exosuit markers (Classic p.9)", img: "classic-guardian-minis.webp", w: 218, h: 252, when: (c) => c.mod("guardians") },
    { set: "classic", qty: "1", name: "Endgame Condition card", note: "Guardians: “Most Guardians” (Classic p.9)", img: "classic-guardians-endgame.webp", w: 172, h: 205, when: (c) => c.mod("guardians") && c.p !== 1 && !c.mod("ic") },
    { set: "fot", qty: "52", name: "Flux Core tokens", note: "Not limited: use any proxy if they run out (Fractures p.3)", img: "fot-flux-cores.webp", w: 148, h: 184 },
    { set: "fot", qty: "20", name: "Operator Workers", note: "Not limited, like all Workers (Fractures p.3)", img: "fot-operators.webp", w: 142, h: 178 },
    { set: "fot", qty: "4", name: "New Warp tiles for the original Paths", note: "1 per Path", img: "fot-new-warp-tiles.webp", w: 320, h: 109 },
    { set: "fot", qty: "18", name: "Technology cards", img: "fot-technology-cards.webp", w: 320, h: 83 },
    { set: "fot", qty: "40", name: "Glitch markers", note: "8 per Path", img: "fot-glitch-markers.webp", w: 320, h: 72 },
    { set: "fot", qty: "1", name: "Flux die", img: "fot-flux-die.webp", w: 129, h: 146 },
    { set: "fot", qty: "1", name: "Glitch die", img: "fot-glitch-die.webp", w: 157, h: 163 },
    { set: "fot", qty: "1", name: "Valley board", img: "fot-valley-board.webp", w: 209, h: 320 },
    { set: "fot", qty: "5", name: "Fracture Device miniboards", note: "1 per Path", img: "fot-fracture-devices.webp", w: 320, h: 136 },
    { set: "fot", qty: "5", name: "Fracture Device Upgrade tiles", note: "1 per Path", img: "fot-fracture-upgrades.webp", w: 320, h: 307 },
    { set: "fot", qty: "1", name: "Path board", note: "Path of Unity", img: "fot-unity-path-board.webp", w: 320, h: 292 },
    { set: "fot", qty: "3", name: "Unity Leader cards", img: "fot-unity-leaders.webp", w: 320, h: 143 },
    { set: "fot", qty: "8", name: "Path markers", note: "Path of Unity", img: "fot-unity-path-markers.webp", w: 132, h: 136 },
    { set: "fot", qty: "1", name: "Player board", note: "Path of Unity", img: "fot-unity-player-board.webp", w: 320, h: 234 },
    { set: "fot", qty: "6", name: "Hex-shaped Exosuit markers", note: "Path of Unity", img: "fot-unity-exosuits.webp", w: 320, h: 81 },
    { set: "fot", qty: "10", name: "Warp tiles", note: "Path of Unity", img: "fot-unity-warp-tiles.webp", w: 320, h: 128 },
    { set: "fot", qty: "6", name: "Paladin miniatures", note: "Path of Unity", img: "fot-paladins.webp", w: 194, h: 228 },
    { set: "fot", qty: "1", name: "Banner with plastic standee", note: "Path of Unity", img: "fot-unity-banner.webp", w: 122, h: 216 },
    { set: "fot", qty: "1", name: "Paladin Exosuit Upgrade tile", note: "Requires the Pioneers of New Earth module", img: "fot-paladin-upgrade.webp", w: 159, h: 211, when: (c) => c.mod("pioneers") },
    { set: "fot", qty: "8", name: "Replacement buildings", note: "215b, 301b, 302b, 303b, 304b, 313b, 314b and 403b replace the base game’s 215, 301–304, 313, 314 and 403 (Fractures p.4)", img: "fot-replacement-buildings.webp", w: 320, h: 104 },
    { set: "fot", qty: "8", name: "New buildings", note: "2 per type. With the Interlocking buildings: 116–118, 216–218, 316–318, 416–418", img: "fot-new-buildings.webp", w: 320, h: 82 },
    { set: "fot", qty: "4", name: "Interlocking buildings", note: "1 per type (pictured with the new buildings)", img: "fot-new-buildings.webp", w: 320, h: 82 },
    { set: "fot", qty: "4", name: "Starting Asset cards", note: "For the Starting Asset Draft variant: shuffle them into the base game’s Asset cards (Fractures p.15)", img: "fot-starting-assets.webp", w: 320, h: 166, when: (c) => c.mod("draft") },
    { set: "fot", qty: "1", name: "Era Zero tile", img: "fot-era-zero.webp", w: 236, h: 166 },
    { set: "fot", qty: "1", name: "Exosuit Bay extension tile", img: "fot-exosuit-bay.webp", w: 111, h: 129 },
    { set: "fot", qty: "4", name: "New Leader cards for the original Paths", img: "fot-new-leaders.webp", w: 320, h: 114 },
    { set: "fot", qty: "1", name: "Scoring pad", note: "Replaces the base pad: Fractures of Time adds three scoring categories (Fractures p.12)", img: "fot-scoring-pad.webp", w: 200, h: 267 },
    { set: "fot", qty: "5", name: "New Superprojects", img: "fot-superprojects.webp", w: 320, h: 207 },
    { set: "fot", qty: "2", name: "New Endgame Condition cards", img: "fot-endgame-cards.webp", w: 276, h: 193, when: (c) => c.p !== 1 && !c.mod("ic") },
    { set: "fot", qty: "9", name: "New Collapsing Capital tiles", note: "3 per Capital Action type", img: "fot-collapsing-capital.webp", w: 320, h: 66 },
    { set: "fot", qty: "16", name: "Variable Anomalies", note: "Variable Anomalies module: replace the base game’s Anomalies, which stay in the box (Fractures p.13)", img: "fot-variable-anomalies.webp", w: 320, h: 86, when: (c) => c.mod("vanom") },
    { set: "fot", qty: "1", name: "New Endgame Condition card", note: "Variable Anomalies module", img: "fot-va-endgame.webp", w: 162, h: 203, when: (c) => c.mod("vanom") && c.p !== 1 && !c.mod("ic") },
    { set: "fot", qty: "4", name: "Anomaly Remover tiles", note: "1 per player. Variable Anomalies module", img: "fot-anomaly-removers.webp", w: 320, h: 187, when: (c) => c.mod("vanom") },
    { set: "fi", qty: "4", name: "New buildings", note: "Neutronide buildings 119, 219, 319 and 419", img: "fi-neutronide-buildings.webp", w: 320, h: 109, when: (c) => c.mod("neu") },
    { set: "fi", qty: "3", name: "Supercharge tiles", img: "fi-supercharge-tiles.webp", w: 320, h: 99, when: (c) => c.mod("hs") },
    { set: "fi", qty: "15", name: "Hypersync tiles", note: "3 for each Path (the Path of Unity needs Fractures of Time)", img: "fi-hypersync-tiles.webp", w: 320, h: 140, when: (c) => c.mod("hs") },
    { set: "fi", qty: "1", name: "Hypersync board", img: "fi-hypersync-board.webp", w: 320, h: 317, when: (c) => c.mod("hs") },
    { set: "fi", qty: "1", name: "New Superproject", note: "Quantum Loops module", img: "fi-ql-superproject.webp", w: 320, h: 186, when: (c) => c.mod("ql") },
    { set: "fi", qty: "5", name: "Quantum Warp tiles", note: "1 for each Path (the Path of Unity needs Fractures of Time)", img: "fi-quantum-warps.webp", w: 187, h: 320, when: (c) => c.mod("ql") },
    { set: "fi", qty: "8", name: "Quantum Loop cards", img: "fi-quantum-loop-cards.webp", w: 320, h: 118, when: (c) => c.mod("ql") },
    { set: "fi", qty: "1", name: "Council Chamber board", img: "fi-council-board.webp", w: 320, h: 302, when: (c) => c.mod("ic") },
    { set: "fi", qty: "4", name: "New buildings", note: "Intrigues of the Council: buildings 120, 220, 320 and 420", img: "fi-ic-buildings.webp", w: 320, h: 143, when: (c) => c.mod("ic") },
    { set: "fi", qty: "1", name: "New Superproject", note: "Intrigues of the Council module", img: "fi-ic-superproject.webp", w: 320, h: 191, when: (c) => c.mod("ic") },
    { set: "fi", qty: "5", name: "Agenda Benefits cards", note: "1 for each Path (the Path of Unity needs Fractures of Time)", img: "fi-agenda-benefits.webp", w: 320, h: 116, when: (c) => c.mod("ic") },
    { set: "fi", qty: "32", name: "Objective tiles", note: "Agenda tiles (52 with the Value tiles). The Agenda grid replaces the Endgame Condition cards, which stay in the box (Future Imperfect p.8–9)", img: "fi-objective-tiles.webp", w: 320, h: 215, when: (c) => c.mod("ic") },
    { set: "fi", qty: "20", name: "Value tiles", note: "Agenda tiles (52 with the Objective tiles)", img: "fi-value-tiles.webp", w: 305, h: 320, when: (c) => c.mod("ic") },
    { set: "fi", qty: "32", name: "Standard Mission cards", note: "8 for each player", img: "fi-standard-missions.webp", w: 320, h: 60, when: (c) => c.mod("ic") },
    { set: "fi", qty: "4", name: "Mission card standees", img: "fi-mission-standees.webp", w: 320, h: 64, when: (c) => c.mod("ic") },
    { set: "fi", qty: "8", name: "Emergency Mission cards", img: "fi-emergency-missions.webp", w: 320, h: 53, when: (c) => c.mod("ic") },
    { set: "fi", qty: "5", name: "Collapsing Capital tiles for the Council Chamber board", img: "fi-council-capital.webp", w: 320, h: 194, when: (c) => c.mod("ic") },
    { set: "solo", qty: "1", name: "Solo banner with plastic standee", note: "Double-sided: Chronobot on one side, Chronossus on the other (Solo p.2)", img: "solo-banner.webp", w: 308, h: 269 },
    { set: "solo", qty: "1", name: "Solo board", note: "Double-sided: Chronobot on one side, Chronossus on the other (Solo p.2)", img: "solo-board.webp", w: 320, h: 238 },
    { set: "solo", qty: "4", name: "Command tokens", note: "Double-sided: Chronobot on one side, Chronossus on the other (Solo p.2)", img: "solo-command-tokens.webp", w: 138, h: 320 },
    { set: "solo", qty: "8", name: "Solo Warp tiles", note: "Double-sided: Chronobot on one side, Chronossus on the other (Solo p.2)", img: "solo-warp-tiles.webp", w: 320, h: 107 },
    { set: "solo", qty: "6", name: "Hex-shaped Exosuit markers", note: "Double-sided: Chronobot on one side, Chronossus on the other (Solo p.2)", img: "solo-exosuit-markers.webp", w: 320, h: 114 },
    { set: "solo", qty: "1", name: "AI die", note: "The Flux die, used to simulate the Solo Opponents’ Actions (Solo p.2)", img: "solo-ai-die.webp", w: 127, h: 129 },
    { set: "solo", qty: "5", name: "Exhausted Energy Core tokens", note: "Chronossus", img: "solo-exhausted-cores.webp", w: 244, h: 273, when: (c) => c.p === 1 && c.mod("chronossus") },
    { set: "solo", qty: "3", name: "Basic Chronossus Action tiles", img: "solo-basic-action-tiles.webp", w: 320, h: 206, when: (c) => c.p === 1 && c.mod("chronossus") },
    { set: "solo", qty: "8", name: "Basic Solo Objective cards", note: "Chronossus", img: "solo-basic-objectives.webp", w: 320, h: 263, when: (c) => c.p === 1 && c.mod("chronossus") },
    { set: "solo", qty: "4", name: "Solo Path markers", note: "Chronossus. Not limited: if they run out, use an unused Path’s markers (Solo p.2)", img: "solo-path-markers.webp", w: 307, h: 110, when: (c) => c.p === 1 && c.mod("chronossus") },
    { set: "solo", qty: "3", name: "Empty Flux Casing tokens", note: "Fractures of Time (Solo p.11)", img: "solo-fot-flux-casings.webp", w: 138, h: 160, when: (c) => c.p === 1 && c.mod("chronossus") && c.has("fot") },
    { set: "solo", qty: "4", name: "Chronossus Action tiles", note: "Fractures of Time (Solo p.11)", img: "solo-fot-action-tiles.webp", w: 320, h: 139, when: (c) => c.p === 1 && c.mod("chronossus") && c.has("fot") },
    { set: "solo", qty: "2", name: "Solo Objective cards", note: "Fractures of Time (Solo p.11)", img: "solo-fot-objectives.webp", w: 300, h: 280, when: (c) => c.p === 1 && c.mod("chronossus") && c.has("fot") },
    { set: "solo", qty: "2", name: "Chronossus Action tiles", note: "Doomsday (Solo p.14)", img: "solo-doom-action-tiles.webp", w: 320, h: 183, when: (c) => c.p === 1 && c.mod("chronossus") && c.mod("doomsday") },
    { set: "solo", qty: "1", name: "Solo Objective card", note: "Doomsday (Solo p.14)", img: "solo-doom-objective.webp", w: 259, h: 182, when: (c) => c.p === 1 && c.mod("chronossus") && c.mod("doomsday") },
    { set: "solo", qty: "2", name: "Chronossus Action tiles", note: "Pioneers of New Earth (Solo p.15)", img: "solo-pio-action-tiles.webp", w: 320, h: 179, when: (c) => c.p === 1 && c.mod("chronossus") && c.mod("pioneers") },
    { set: "solo", qty: "1", name: "Solo Objective card", note: "Pioneers of New Earth (Solo p.15)", img: "solo-pio-objective.webp", w: 259, h: 172, when: (c) => c.p === 1 && c.mod("chronossus") && c.mod("pioneers") },
    { set: "solo", qty: "1", name: "Chronossus Exosuit Upgrade board", note: "Pioneers of New Earth (Solo p.15)", img: "solo-pio-upgrade-board.webp", w: 237, h: 313, when: (c) => c.p === 1 && c.mod("chronossus") && c.mod("pioneers") },
    { set: "solo", qty: "1", name: "Chronossus Action tile", note: "Guardians of the Council (Solo p.16)", img: "solo-guard-action-tile.webp", w: 220, h: 158, when: (c) => c.p === 1 && c.mod("chronossus") && c.mod("guardians") },
    { set: "solo", qty: "1", name: "Solo Objective card", note: "Guardians of the Council (Solo p.16)", img: "solo-guard-objective.webp", w: 259, h: 177, when: (c) => c.p === 1 && c.mod("chronossus") && c.mod("guardians") },
    { set: "solo", qty: "2", name: "Chronossus Action tiles", note: "Hypersync Future Actions (Solo p.17)", img: "solo-hs-action-tiles.webp", w: 320, h: 209, when: (c) => c.p === 1 && c.mod("chronossus") && c.mod("hs") },
    { set: "solo", qty: "3", name: "Solo Hypersync tiles", note: "Hypersync Future Actions (Solo p.17)", img: "solo-hs-tiles.webp", w: 265, h: 236, when: (c) => c.p === 1 && c.mod("chronossus") && c.mod("hs") }
  ]
};
