/* =============================================================================
   Eldritch Horror — Components glossary data (standard format v1; rendered by js/comp-widget.js)
   Sources (printed page numbers): Base Rulebook p.3 (Components) · Forsaken Lore p.1 · Mountains of
   Madness p.3 (with "Using This Expansion" p.2) · Strange Remnants p.1 · Under the Pyramids p.3 (p.2) ·
   Signs of Carcosa p.1 · The Dreamlands p.3 (p.2) · Cities in Ruin p.1 · Masks of Nyarlathotep p.3
   (p.2, Preludes p.4, Personal Stories p.6).
   - Pictures are cropped from the picture pages (base, MoM, UtP, The Dreamlands, Masks). Forsaken Lore,
     Strange Remnants, Signs of Carcosa and Cities in Ruin list their components as text only, so those items
     have no picture (except Strange Remnants' Round Overview card, pictured on its components page).
   - Counts and names are as printed (sentence case), including the book's own spellings ("Ancient Ones
     Sheets" in MoM, "3 Dream Portal Token" in The Dreamlands, "Mystic Ruin" in Masks).
   - MoM, UtP, The Dreamlands and Masks print no total for their Encounter Cards panel, so those items have
     no count; the breakdown is in the note, in the rulebook's reading order. Every Encounter cards picture
     shows the first row of card backs only, so that no sub-caption text is in the picture.
   - No expansion replaces a base-game component. Gating: Prelude cards are hidden with the No Prelude
     variant (they still show in Campaign Mode, which always plays two Preludes: Masks p.7); Personal
     Mission and Reward/Consequence cards show only with Personal Stories or Campaign Mode (Masks p.6–7).
   ============================================================================= */
window.AID_COMPONENTS = {
  sets: [
    { id: "base", name: "Eldritch Horror", src: "Base Rulebook p.3" },
    { id: "fl", name: "Forsaken Lore", src: "FL p.1", when: (c) => c.has("fl") },
    { id: "mom", name: "Mountains of Madness", src: "MoM p.3", when: (c) => c.has("mom") },
    { id: "sr", name: "Strange Remnants", src: "SR p.1", when: (c) => c.has("sr") },
    { id: "utp", name: "Under the Pyramids", src: "UtP p.3", when: (c) => c.has("utp") },
    { id: "soc", name: "Signs of Carcosa", src: "SoC p.1", when: (c) => c.has("soc") },
    { id: "td", name: "The Dreamlands", src: "The Dreamlands p.3", when: (c) => c.has("td") },
    { id: "cir", name: "Cities in Ruin", src: "CiR p.1", when: (c) => c.has("cir") },
    { id: "mon", name: "Masks of Nyarlathotep", src: "Masks p.3", when: (c) => c.has("mon") }
  ],
  items: [
    /* ---- Base game (Base Rulebook p.3) ---- */
    { set: "base", qty: "1", name: "Game board", img: "base-board.webp", w: 320, h: 216 },
    { set: "base", qty: "12", name: "Investigator sheets with matching tokens and plastic stands", img: "base-investigators.webp", w: 320, h: 182 },
    { set: "base", qty: "4", name: "Ancient One sheets", img: "base-ancient-ones.webp", w: 264, h: 311 },
    { set: "base", qty: "122", name: "Encounter cards", note: "8 America, 8 Europe, 8 Asia/Australia, 12 General, 24 Other World, 18 Expedition (6 backs, 3 each), 12 Special (2 backs, 6 each), 32 Research (4 backs, 8 each)", img: "base-encounters.webp", w: 320, h: 108 },
    { set: "base", qty: "51", name: "Mythos cards", note: "21 yellow, 18 green, and 12 blue", img: "base-mythos.webp", w: 215, h: 306 },
    { set: "base", qty: "16", name: "Mystery cards", note: "4 backs, 4 each", img: "base-mysteries.webp", w: 211, h: 306 },
    { set: "base", qty: "14", name: "Artifact cards", img: "base-artifacts.webp", w: 163, h: 229 },
    { set: "base", qty: "40", name: "Asset cards", img: "base-assets.webp", w: 166, h: 229 },
    { set: "base", qty: "36", name: "Condition cards", img: "base-conditions.webp", w: 163, h: 230 },
    { set: "base", qty: "20", name: "Spell cards", img: "base-spells.webp", w: 166, h: 230 },
    { set: "base", qty: "43", name: "Monster tokens", note: "34 normal, 9 epic", img: "base-monsters.webp", w: 255, h: 202 },
    { set: "base", qty: "1", name: "Lead Investigator token", img: "base-lead-investigator.webp", w: 218, h: 140 },
    { set: "base", qty: "20", name: "Travel Ticket tokens", note: "8 train, 12 ship", img: "base-travel-tickets.webp", w: 233, h: 142 },
    { set: "base", qty: "30", name: "Improvement tokens", note: "6 for each skill", img: "base-improvements.webp", w: 242, h: 141 },
    { set: "base", qty: "1", name: "Mystery token", img: "base-mystery-token.webp", w: 196, h: 191 },
    { set: "base", qty: "36", name: "Clue tokens", img: "base-clues.webp", w: 150, h: 138 },
    { set: "base", qty: "20", name: "Eldritch tokens", img: "base-eldritch.webp", w: 154, h: 138 },
    { set: "base", qty: "9", name: "Gate tokens", img: "base-gates.webp", w: 227, h: 219 },
    { set: "base", qty: "4", name: "Reference cards", img: "base-reference-cards.webp", w: 227, h: 152 },
    { set: "base", qty: "78", name: "Health and Sanity tokens", note: "30 “1 Health”, 12 “3 Health”, 24 “1 Sanity”, 12 “3 Sanity”", img: "base-health-sanity.webp", w: 218, h: 127 },
    { set: "base", qty: "4", name: "Rumor tokens", img: "base-rumors.webp", w: 187, h: 167 },
    { set: "base", qty: "1", name: "Omen token", img: "base-omen.webp", w: 169, h: 163 },
    { set: "base", qty: "1", name: "Doom token", img: "base-doom.webp", w: 175, h: 171 },
    { set: "base", qty: "4", name: "Dice", img: "base-dice.webp", w: 148, h: 141 },
    { set: "base", qty: "1", name: "Active Expedition token", img: "base-active-expedition.webp", w: 215, h: 192 },

    /* ---- Forsaken Lore (FL p.1: a text list, no pictures) ---- */
    { set: "fl", qty: "1", name: "Ancient One sheet" },
    { set: "fl", qty: "148", name: "Encounter cards", note: "8 America, 8 Europe, 8 Asia/Australia, 4 General, 6 Other World, 6 Expedition (6 unique backs), 20 Special (4 unique backs), 88 Research (5 unique backs)" },
    { set: "fl", qty: "14", name: "Mystery cards", note: "5 unique backs" },
    { set: "fl", qty: "6", name: "Mythos cards" },
    { set: "fl", qty: "8", name: "Artifact cards" },
    { set: "fl", qty: "16", name: "Asset cards" },
    { set: "fl", qty: "24", name: "Condition cards" },
    { set: "fl", qty: "28", name: "Spell cards" },
    { set: "fl", qty: "8", name: "Monster tokens", note: "1 normal, 7 epic" },
    { set: "fl", qty: "6", name: "Health and Sanity tokens", note: "4 health, 2 sanity" },

    /* ---- Mountains of Madness (MoM p.3; usage notes from "Using This Expansion", MoM p.2) ---- */
    { set: "mom", qty: "1", name: "Antarctica side board", note: "Used by the Rise of the Elder Things Ancient One and the <i>Doomsayer From Antarctica</i> Prelude; otherwise returned to the box (MoM p.2)", img: "mom-side-board.webp", w: 320, h: 206 },
    { set: "mom", qty: "8", name: "Investigator sheets with matching tokens and plastic stands", img: "mom-investigators.webp", w: 320, h: 172 },
    { set: "mom", qty: "2", name: "Ancient Ones sheets", img: "mom-ancient-ones.webp", w: 256, h: 305 },
    { set: "mom", qty: "26", name: "Mythos cards", img: "mom-mythos.webp", w: 205, h: 305 },
    { set: "mom", name: "Encounter cards", note: "4 General, 4 Americas, 4 Europe, 4 Asia/Australia, 6 Expedition (3 unique backs), 6 Other World, 48 Research (2 unique backs), 24 Special (3 unique backs), 16 Outpost, 16 Mountains, 16 Antarctica Research. The Outpost, Mountain and Antarctica Research cards are used only with the Antarctica side board (MoM p.2)", img: "mom-encounters.webp", w: 320, h: 118 },
    { set: "mom", qty: "14", name: "Mystery cards", note: "2 unique backs", img: "mom-mysteries.webp", w: 318, h: 207 },
    { set: "mom", qty: "12", name: "Adventure cards", note: "3 unique backs. Used by the <i>Doomsayer From Antarctica</i> Prelude; otherwise returned to the box (MoM p.2)", img: "mom-adventures.webp", w: 319, h: 208 },
    { set: "mom", qty: "8", name: "Artifact cards", img: "mom-artifacts.webp", w: 169, h: 228 },
    { set: "mom", qty: "16", name: "Asset cards", img: "mom-assets.webp", w: 169, h: 228 },
    { set: "mom", qty: "16", name: "Spell cards", img: "mom-spells.webp", w: 172, h: 228 },
    { set: "mom", qty: "42", name: "Unique Asset cards", img: "mom-unique-assets.webp", w: 172, h: 229 },
    { set: "mom", qty: "32", name: "Condition cards", img: "mom-conditions.webp", w: 172, h: 229 },
    { set: "mom", qty: "6", name: "Prelude cards", img: "mom-preludes.webp", w: 224, h: 310, when: (c) => !c.mod("noPrelude") || c.mod("campaign") },
    { set: "mom", qty: "4", name: "Round Overview cards", img: "mom-round-overview.webp", w: 227, h: 310 },
    { set: "mom", qty: "6", name: "Clue tokens", note: "All six match spaces on the Antarctica side board and are used only with it (MoM p.2)", img: "mom-clues.webp", w: 163, h: 177 },
    { set: "mom", qty: "8", name: "Focus tokens", img: "mom-focus.webp", w: 163, h: 178 },
    { set: "mom", qty: "1", name: "Adventure token", img: "mom-adventure-token.webp", w: 178, h: 196 },
    { set: "mom", qty: "1", name: "Mystery token", img: "mom-mystery-token.webp", w: 194, h: 196 },
    { set: "mom", qty: "6", name: "Gate tokens", note: "Three match spaces on the Antarctica side board and are used only with it (MoM p.2)", img: "mom-gates.webp", w: 227, h: 209 },
    { set: "mom", qty: "14", name: "Monster tokens and 8 Epic Monster tokens", img: "mom-monsters.webp", w: 248, h: 209 },

    /* ---- Strange Remnants (SR p.1: a text list; its Round Overview card is pictured on the same page) ---- */
    { set: "sr", qty: "4", name: "Investigator sheets" },
    { set: "sr", qty: "1", name: "Ancient One sheet" },
    { set: "sr", qty: "86", name: "Encounter cards", note: "4 General, 4 America, 4 Europe, 4 Asia/Australia, 6 Other World, 20 Mystic Ruins (4 unique backs), 20 Special (2 unique backs), 24 Research. The Mystic Ruins cards are used by the Syzygy Ancient One and the <i>In Cosmic Alignment</i> Prelude; otherwise returned to the box (SR p.1)" },
    { set: "sr", qty: "6", name: "Mystery cards" },
    { set: "sr", qty: "6", name: "Adventure cards", note: "Used by the <i>In Cosmic Alignment</i> Prelude; otherwise returned to the box (SR p.1)" },
    { set: "sr", qty: "20", name: "Mythos cards" },
    { set: "sr", qty: "4", name: "Prelude cards", when: (c) => !c.mod("noPrelude") || c.mod("campaign") },
    { set: "sr", qty: "4", name: "Round Overview cards", img: "sr-round-overview.webp", w: 217, h: 320 },
    { set: "sr", qty: "4", name: "Artifact cards" },
    { set: "sr", qty: "16", name: "Asset cards" },
    { set: "sr", qty: "16", name: "Condition cards" },
    { set: "sr", qty: "16", name: "Spell cards" },
    { set: "sr", qty: "24", name: "Unique Asset cards" },
    { set: "sr", qty: "4", name: "Investigator tokens with plastic stands" },
    { set: "sr", qty: "6", name: "Monster tokens", note: "4 normal, 2 epic" },
    { set: "sr", qty: "6", name: "Health tokens" },
    { set: "sr", qty: "4", name: "Sanity tokens" },
    { set: "sr", qty: "12", name: "Focus tokens" },
    { set: "sr", qty: "1", name: "Adventure token" },
    { set: "sr", qty: "1", name: "Mystic Ruins token" },

    /* ---- Under the Pyramids (UtP p.3; usage notes from UtP p.2) ---- */
    { set: "utp", qty: "1", name: "Egypt side board", note: "Used by the Nephren-Ka Ancient One and the <i>Under the Pyramids</i> Prelude; otherwise returned to the box (UtP p.2)", img: "utp-side-board.webp", w: 320, h: 206 },
    { set: "utp", qty: "8", name: "Investigator sheets with matching tokens and plastic stands", img: "utp-investigators.webp", w: 320, h: 172 },
    { set: "utp", qty: "2", name: "Ancient One sheets", img: "utp-ancient-ones.webp", w: 256, h: 305 },
    { set: "utp", qty: "22", name: "Mythos cards", img: "utp-mythos.webp", w: 205, h: 305 },
    { set: "utp", name: "Encounter cards", note: "4 Americas, 4 Europe, 4 Asia/Australia, 16 Egypt, 16 Africa, 4 General, 12 Expedition (9 unique backs), 6 Other World, 48 Research (2 unique backs), 40 Special (4 unique backs). The Egypt and Africa cards are used only with the Egypt side board (UtP p.2)", img: "utp-encounters.webp", w: 320, h: 94 },
    { set: "utp", qty: "12", name: "Mystery cards", note: "2 unique backs", img: "utp-mysteries.webp", w: 318, h: 207 },
    { set: "utp", qty: "6", name: "Adventure cards", note: "Used by the <i>Under the Pyramids</i> Prelude; otherwise returned to the box (UtP p.2)", img: "utp-adventures.webp", w: 318, h: 209 },
    { set: "utp", qty: "6", name: "Prelude cards", img: "utp-preludes.webp", w: 224, h: 309, when: (c) => !c.mod("noPrelude") || c.mod("campaign") },
    { set: "utp", qty: "4", name: "Artifact cards", img: "utp-artifacts.webp", w: 171, h: 228 },
    { set: "utp", qty: "16", name: "Asset cards", img: "utp-assets.webp", w: 170, h: 228 },
    { set: "utp", qty: "24", name: "Spell cards", img: "utp-spells.webp", w: 174, h: 228 },
    { set: "utp", qty: "35", name: "Unique Asset cards", img: "utp-unique-assets.webp", w: 172, h: 228 },
    { set: "utp", qty: "16", name: "Condition cards", img: "utp-conditions.webp", w: 173, h: 228 },
    { set: "utp", qty: "7", name: "Monster tokens and 5 Epic Monster tokens", img: "utp-monsters.webp", w: 251, h: 210 },
    { set: "utp", qty: "12", name: "Health and Sanity tokens", img: "utp-health-sanity.webp", w: 202, h: 138 },
    { set: "utp", qty: "6", name: "Clue tokens", note: "All six match spaces on the Egypt side board and are used only with it (UtP p.2)", img: "utp-clues.webp", w: 151, h: 157 },
    { set: "utp", qty: "20", name: "Impairment tokens", img: "utp-impairments.webp", w: 233, h: 190 },
    { set: "utp", qty: "1", name: "Adventure token", img: "utp-adventure-token.webp", w: 180, h: 198 },
    { set: "utp", qty: "1", name: "Active Expedition token", img: "utp-active-expedition.webp", w: 202, h: 208 },
    { set: "utp", qty: "6", name: "Gate tokens", note: "Three match spaces on the Egypt side board and are used only with it (UtP p.2)", img: "utp-gates.webp", w: 230, h: 211 },

    /* ---- Signs of Carcosa (SoC p.1: a text list, no pictures) ---- */
    { set: "soc", qty: "4", name: "Investigator sheets" },
    { set: "soc", qty: "1", name: "Ancient One sheet" },
    { set: "soc", qty: "84", name: "Encounter cards", note: "4 General, 4 America, 4 Europe, 4 Asia/Australia, 6 Expedition, 6 Other World, 24 Research, 32 Special (3 unique backs)" },
    { set: "soc", qty: "8", name: "Mystery cards" },
    { set: "soc", qty: "24", name: "Mythos cards" },
    { set: "soc", qty: "4", name: "Prelude cards", when: (c) => !c.mod("noPrelude") || c.mod("campaign") },
    { set: "soc", qty: "4", name: "Artifact cards" },
    { set: "soc", qty: "16", name: "Asset cards" },
    { set: "soc", qty: "28", name: "Condition cards" },
    { set: "soc", qty: "12", name: "Spell cards" },
    { set: "soc", qty: "16", name: "Unique Asset cards" },
    { set: "soc", qty: "4", name: "Investigator tokens with plastic stands" },
    { set: "soc", qty: "8", name: "Monster tokens", note: "6 normal, 2 epic" },
    { set: "soc", qty: "20", name: "Impairment tokens" },

    /* ---- The Dreamlands (The Dreamlands p.3; usage notes from The Dreamlands p.2) ---- */
    { set: "td", qty: "1", name: "Dreamlands side board", note: "Used by the Hypnos Ancient One and the <i>Otherworldly Dreams</i> Prelude; otherwise returned to the box (The Dreamlands p.2)", img: "td-side-board.webp", w: 225, h: 320 },
    { set: "td", qty: "8", name: "Investigator sheets with matching tokens and plastic stands", img: "td-investigators.webp", w: 320, h: 172 },
    { set: "td", qty: "2", name: "Ancient One sheets", img: "td-ancient-ones.webp", w: 261, h: 308 },
    { set: "td", qty: "12", name: "Mystery cards", note: "2 unique backs", img: "td-mysteries.webp", w: 318, h: 208 },
    { set: "td", qty: "8", name: "Adventure cards", note: "Used by the <i>Otherworldly Dreams</i> Prelude; otherwise returned to the box (The Dreamlands p.2)", img: "td-adventures.webp", w: 318, h: 208 },
    { set: "td", qty: "4", name: "Artifact cards", img: "td-artifacts.webp", w: 171, h: 227 },
    { set: "td", qty: "16", name: "Asset cards", img: "td-assets.webp", w: 170, h: 227 },
    { set: "td", qty: "12", name: "Spell cards", img: "td-spells.webp", w: 174, h: 229 },
    { set: "td", qty: "25", name: "Unique Asset cards", img: "td-unique-assets.webp", w: 172, h: 229 },
    { set: "td", qty: "19", name: "Condition cards", img: "td-conditions.webp", w: 172, h: 229 },
    { set: "td", name: "Encounter cards", note: "4 Americas, 4 Europe, 4 Asia/Australia, 4 General, 16 Dreamlands, 6 Other World, 48 Research (2 unique backs), 24 Special (3 unique backs), 20 Dream-Quest (4 unique backs). The Dreamlands and Dream-Quest cards are used only with the Dreamlands side board (The Dreamlands p.2)", img: "td-encounters.webp", w: 320, h: 155 },
    { set: "td", qty: "24", name: "Mythos cards", img: "td-mythos.webp", w: 221, h: 309 },
    { set: "td", qty: "6", name: "Prelude cards", img: "td-preludes.webp", w: 224, h: 313, when: (c) => !c.mod("noPrelude") || c.mod("campaign") },
    { set: "td", qty: "4", name: "Round Overview cards", img: "td-round-overview.webp", w: 224, h: 313 },
    { set: "td", qty: "6", name: "Monster tokens and 5 Epic Monster tokens", img: "td-monsters.webp", w: 248, h: 207 },
    { set: "td", qty: "3", name: "Dream Portal token", note: "Used only with the Dreamlands side board (The Dreamlands p.2)", img: "td-dream-portals.webp", w: 320, h: 239 },
    { set: "td", qty: "1", name: "Adventure token", img: "td-adventure-token.webp", w: 180, h: 197 },
    { set: "td", qty: "1", name: "Dream-Quest token", note: "Used only with the Dreamlands side board (The Dreamlands p.2)", img: "td-dream-quest-token.webp", w: 201, h: 206 },
    { set: "td", qty: "3", name: "Gate tokens", note: "All three match spaces on the Dreamlands side board and are used only with it (The Dreamlands p.2)", img: "td-gates.webp", w: 228, h: 209 },
    { set: "td", qty: "4", name: "Health and Sanity tokens", img: "td-health-sanity.webp", w: 208, h: 139 },
    { set: "td", qty: "7", name: "Clue tokens", note: "All seven match spaces on the Dreamlands side board and are used only with it (The Dreamlands p.2)", img: "td-clues.webp", w: 160, h: 161 },
    { set: "td", qty: "12", name: "Focus tokens", img: "td-focus.webp", w: 160, h: 161 },

    /* ---- Cities in Ruin (CiR p.1: a text list, no pictures) ---- */
    { set: "cir", qty: "4", name: "Investigator sheets" },
    { set: "cir", qty: "1", name: "Ancient One sheet" },
    { set: "cir", qty: "76", name: "Encounter cards", note: "4 General, 4 America, 4 Europe, 4 Asia/Australia, 6 Expedition, 6 Other World, 16 Devastation, 24 Research, 8 Special" },
    { set: "cir", qty: "6", name: "Mystery cards" },
    { set: "cir", qty: "24", name: "Mythos cards" },
    { set: "cir", qty: "16", name: "Disaster cards" },
    { set: "cir", qty: "4", name: "Prelude cards", when: (c) => !c.mod("noPrelude") || c.mod("campaign") },
    { set: "cir", qty: "4", name: "Artifact cards" },
    { set: "cir", qty: "16", name: "Asset cards" },
    { set: "cir", qty: "20", name: "Condition cards" },
    { set: "cir", qty: "12", name: "Spell cards" },
    { set: "cir", qty: "24", name: "Unique Asset cards" },
    { set: "cir", qty: "4", name: "Investigator tokens with plastic stands" },
    { set: "cir", qty: "10", name: "Monster tokens", note: "4 normal, 6 epic" },
    { set: "cir", qty: "8", name: "Devastation tokens" },
    { set: "cir", qty: "8", name: "Health tokens" },
    { set: "cir", qty: "6", name: "Sanity tokens" },
    { set: "cir", qty: "8", name: "Eldritch tokens" },

    /* ---- Masks of Nyarlathotep (Masks p.3; usage notes from Masks p.2, p.4 and p.6) ---- */
    { set: "mon", qty: "7", name: "Investigator sheets with matching tokens and plastic stands", img: "mon-investigators.webp", w: 320, h: 172 },
    { set: "mon", qty: "2", name: "Ancient One sheets", img: "mon-ancient-ones.webp", w: 263, h: 308 },
    { set: "mon", qty: "10", name: "Mystery cards", note: "2 unique backs", img: "mon-mysteries.webp", w: 318, h: 210 },
    { set: "mon", qty: "12", name: "Adventure cards", note: "4 unique backs. Used by the Nyarlathotep Ancient One; otherwise returned to the box (Masks p.2)", img: "mon-adventures.webp", w: 318, h: 210 },
    { set: "mon", name: "Encounter cards", note: "8 General, 8 Americas, 8 Europe, 8 Asia/Australia, 6 Other World, 20 Mystic Ruin (4 unique backs), 48 Research (2 unique backs), 16 Special (2 unique backs). The Mystic Ruins cards are used by the Antediluvium Ancient One and <i>The Stars Align</i> Prelude; otherwise returned to the box (Masks p.2)", img: "mon-encounters.webp", w: 320, h: 116 },
    { set: "mon", qty: "20", name: "Mythos cards", img: "mon-mythos.webp", w: 223, h: 308 },
    { set: "mon", qty: "14", name: "Prelude cards", note: "Four first appeared in earlier expansions: <i>Beginning of the End</i> (MoM), <i>The Dunwich Horror</i> (SR), <i>Twin Blasphemies of the Black Goat</i> (The Dreamlands) and <i>Call of Cthulhu</i> (UtP). If you play with that expansion too, leave the duplicate out of the Prelude deck (Masks p.4)", img: "mon-preludes.webp", w: 226, h: 313, when: (c) => !c.mod("noPrelude") || c.mod("campaign") },
    { set: "mon", qty: "8", name: "Round Overview cards", img: "mon-round-overview.webp", w: 226, h: 312 },
    { set: "mon", qty: "10", name: "Monster tokens and 5 Epic Monster tokens", img: "mon-monsters.webp", w: 250, h: 207 },
    { set: "mon", qty: "4", name: "Artifact cards", img: "mon-artifacts.webp", w: 170, h: 227 },
    { set: "mon", qty: "16", name: "Asset cards", img: "mon-assets.webp", w: 170, h: 227 },
    { set: "mon", qty: "4", name: "Spell cards", img: "mon-spells.webp", w: 173, h: 230 },
    { set: "mon", qty: "28", name: "Unique Asset cards", img: "mon-unique-assets.webp", w: 174, h: 230 },
    { set: "mon", qty: "24", name: "Condition cards", img: "mon-conditions.webp", w: 174, h: 230 },
    { set: "mon", qty: "55", name: "Personal Mission cards", note: "Personal Stories: one for each investigator, including those from the base game and earlier expansions, matched by the art on the Investigator sheet (Masks p.6)", img: "mon-personal-missions.webp", w: 179, h: 230, when: (c) => c.mod("stories") || c.mod("campaign") },
    { set: "mon", qty: "55", name: "Reward/Consequence cards", note: "Personal Stories: one double-sided card for each investigator (Masks p.6)", img: "mon-reward-consequence.webp", w: 175, h: 230, when: (c) => c.mod("stories") || c.mod("campaign") },
    { set: "mon", qty: "8", name: "Eldritch tokens", img: "mon-eldritch.webp", w: 162, h: 166 },
    { set: "mon", qty: "16", name: "Focus tokens", img: "mon-focus.webp", w: 161, h: 166 },
    { set: "mon", qty: "20", name: "Resource tokens", img: "mon-resources.webp", w: 161, h: 166 },
    { set: "mon", qty: "1", name: "Adventure token", img: "mon-adventure-token.webp", w: 180, h: 197 },
    { set: "mon", qty: "1", name: "Mystic Ruins token", img: "mon-mystic-ruins-token.webp", w: 201, h: 206 },
    { set: "mon", qty: "3", name: "Gate tokens", img: "mon-gates.webp", w: 228, h: 211 }
  ]
};
