/* =============================================================================
   Twilight Imperium 3rd Edition — Components glossary data (standard v1; rendered by js/comp-widget.js)
   Sources: Base p.4 (contents list) with pictures from the component overview, Base p.4–6 (Leader counters
   from p.34, Domain Counters from p.33, where the rulebook pictures them) · SE p.4 (contents) with pictures
   from SE p.5–6 (the Imperial II card from SE p.17) · SoT p.5 (contents) with pictures from SoT p.6–8.
   Counts and names follow the contents lists. Option components appear only with their option; Fall of the
   Empire hides what its Agenda and Scenario Objective cards replace (SoT p.14) and uses no Shattered Empire
   component except a seventh colour (SoT p.14–15).
   ============================================================================= */
window.AID_COMPONENTS = {
  sets: [
    { id: "base", name: "Twilight Imperium 3rd Edition", src: "Base p.4–6", fig: "#fad575" },
    { id: "se", name: "Shattered Empire", src: "SE p.4–6", fig: "#f8d58a", when: (c) => c.has("se") && (!c.fote || c.p === 7) },
    { id: "sot", name: "Shards of the Throne", src: "SoT p.5–8", fig: "#fad48b", when: (c) => c.has("sot") }
  ],
  items: [
    /* ---- base game (Base p.4 list) ---- */
    { set: "base", qty: "43", name: "Hexagonal board tiles", note: "The systems: Home Systems have a yellow inner border, Special Systems a red one (Base p.4)",
      img: "base-map-hexes.webp", w: 320, h: 260 },
    { set: "base", qty: "6", name: "Frames of plastic components", note: "One per colour (six colours), each with 5 Dreadnoughts, 4 Carriers, 8 Cruisers, 8 Destroyers, 2 War Suns, 12 Ground Forces, 10 Fighters, 6 PDS and 3 Space Docks",
      img: "base-plastic-units.webp", w: 320, h: 278 },
    { set: "base", qty: "10", name: "Race sheets", img: "base-race-sheets.webp", w: 320, h: 182 },
    { set: "base", qty: "144", name: "Technology cards", note: "24 each in six decks separated by colour",
      img: "base-technology-cards.webp", w: 320, h: 168 },
    { set: "base", qty: "51", name: "Planet cards", img: "base-planet-cards.webp", w: 320, h: 168 },
    { set: "base", qty: "103", name: "Action cards", img: "base-action-cards.webp", w: 320, h: 168 },
    { set: "base", qty: "60", name: "Political cards", img: "base-political-cards.webp", w: 320, h: 170, when: (c) => !c.fote },
    { set: "base", qty: "30", name: "Objective cards (Secret and Public)",
      img: "base-objective-cards.webp", w: 320, h: 168, when: (c) => !c.fote },
    { set: "base", qty: "20", name: "Trade cards", note: "2 each for 10 races", img: "base-trade-cards.webp", w: 320, h: 169 },
    { set: "base", qty: "8", name: "Cardboard Strategy cards",
      img: "base-strategy-cards.webp", w: 320, h: 303, when: (c) => (c.raw || []).some((id) => ["initiative", "diplomacy", "political", "logistics", "trade", "warfare", "technology", "imperial"].indexOf(id) !== -1) },
    { set: "base", qty: "160", name: "Command counters", note: "16 each for 10 races", img: "base-command-counters.webp", w: 320, h: 177 },
    { set: "base", qty: "150", name: "Control markers", note: "15 each for 10 races", img: "base-control-markers.webp", w: 320, h: 149 },
    { set: "base", qty: "8", name: "Bonus counters", img: "base-bonus-counters.webp", w: 282, h: 224 },
    { set: "base", qty: "40", name: "Trade Goods counters", img: "base-trade-goods.webp", w: 282, h: 255 },
    { set: "base", qty: "23", name: "Fighter supplement counters", img: "base-fighter-supplement.webp", w: 184, h: 184 },
    { set: "base", qty: "23", name: "Ground Force supplement counters", img: "base-gf-supplement.webp", w: 185, h: 184 },
    { set: "base", qty: "1", name: "Speaker token", img: "base-speaker-token.webp", w: 320, h: 198 },
    { set: "base", qty: "1", name: "Victory Point Track", note: "0–10 on one side, 0–14 on the other for the Long War (Base p.6)",
      img: "base-vp-track.webp", w: 320, h: 56 },
    { set: "base", qty: "4", name: "10-sided dice", note: "A “0” result is 10" },
    { set: "base", qty: "30", name: "Leader counters", note: "Pictured on Base p.34", src: "Base p.34",
      img: "base-leader-counters.webp", w: 320, h: 191, when: (c) => c.mod("leaders") },
    { set: "base", qty: "44", name: "Domain counters", note: "Distant Suns; pictured on Base p.33", src: "Base p.33",
      img: "base-domain-counters.webp", w: 320, h: 162, when: (c) => c.mod("ds") },

    /* ---- Shattered Empire (SE p.4 list) ---- */
    { set: "se", qty: "28", name: "New system tiles", note: "Includes the Ion Storms, Hope’s End, 4 new Home Systems and the Wormhole Nexus",
      img: "se-system-tiles.webp", w: 320, h: 217, when: (c) => !c.fote },
    { set: "se", qty: "2", name: "New sets of plastic units", note: "Each: 5 Dreadnoughts, 4 Carriers, 8 Cruisers, 8 Destroyers, 2 War Suns, 12 Ground Forces, 10 Fighters, 6 PDS and 3 Space Docks — the 7th and 8th colours",
      img: "se-plastic-units.webp", w: 319, h: 279, when: (c) => !c.fote },
    { set: "se", qty: "2", name: "New sets of plastic units", note: "Fall of the Empire with 7 players uses one of these colours, with its Technology deck — this page’s reading of SoT p.14–15, which needs Shattered Empire for a seventh player but bars its other components",
      img: "se-plastic-units.webp", w: 319, h: 279, when: (c) => !!c.fote },
    { set: "se", qty: "4", name: "New race sheets", img: "se-race-sheets.webp", w: 320, h: 196, when: (c) => !c.fote },
    { set: "se", qty: "64", name: "Command counters", note: "16 for each of the four new races", when: (c) => !c.fote },
    { set: "se", qty: "88", name: "Control markers", note: "88 as printed on SE p.4, though its own breakdown — 14 for each of the four new races plus 2 more for each of the 10 original races — adds up to 76, and SE p.6 gives each new race 15",
      when: (c) => !c.fote },
    { set: "se", qty: "12", name: "Leader counters", note: "3 for each of the four new races", when: (c) => c.mod("leaders") },
    { set: "se", qty: "8", name: "New variant Strategy cards", note: "The white set; with the full set in play they replace the original eight (SE p.9)",
      img: "se-strategy-cards.webp", w: 320, h: 290,
      when: (c) => !c.fote && (c.raw || []).some((id) => ["leadership", "diplomacy2", "assembly", "production", "trade2", "warfare2", "technology2", "bureaucracy"].indexOf(id) !== -1) },
    { set: "se", qty: "1", name: "Variant Imperial Strategy card", note: "Imperial II — replaces the original Imperial card; needs Age of Empire (SE p.9, p.17)", src: "SE p.17",
      img: "se-imperial2.webp", w: 278, h: 320, when: (c) => !!(c.uses && c.uses("imperial2")) },
    { set: "se", qty: "1", name: "High Alert token", note: "For Warfare II", img: "se-high-alert.webp", w: 105, h: 99, when: (c) => !!(c.uses && c.uses("warfare2")) },
    { set: "se", qty: "8", name: "New Trade Contract cards", when: (c) => !c.fote },
    { set: "se", qty: "28", name: "New Objective cards", note: "New Stage I and Stage II decks (Variant Objectives), 3 Secret Objectives, and Special Objectives for Artifacts and Voice of the Council (SE p.5)",
      img: "se-objective-cards.webp", w: 320, h: 186, when: (c) => !c.fote },
    { set: "se", qty: "40", name: "New Action cards", note: "The expansion also provides replacements for the base game’s Direct Hit (4) and Ruinous Tariff (1) cards (SE p.4)",
      img: "se-action-cards.webp", w: 185, h: 193, when: (c) => !c.fote },
    { set: "se", qty: "32", name: "New Political cards", note: "The expansion also provides a replacement Open the Trade Routes card (SE p.4)",
      img: "se-political-cards.webp", w: 185, h: 193, when: (c) => !c.fote },
    { set: "se", qty: "98", name: "Technology cards", note: "Including 2 new Technology decks in grey and orange, and replacement Advanced Fighters, Micro Technology and Assault Cannon (SE p.4)" ,
      img: "se-technology-cards.webp", w: 320, h: 175, when: (c) => !c.fote },
    { set: "se", qty: "98", name: "Technology cards", note: "Fall of the Empire with 7 players uses only the seventh colour’s grey or orange deck — this page’s reading of SoT p.14–15",
      img: "se-technology-cards.webp", w: 320, h: 175, when: (c) => !!c.fote },
    { set: "se", qty: "14", name: "Race-specific Technology cards", img: "se-race-techs.webp", w: 320, h: 175, when: (c) => c.mod("rst") },
    { set: "se", qty: "28", name: "New Planet cards", img: "se-planet-cards.webp", w: 320, h: 186, when: (c) => !c.fote },
    { set: "se", qty: "16", name: "Facility cards", note: "8 Colonies and 8 Refineries", img: "se-facility-cards.webp", w: 320, h: 178, when: (c) => c.mod("facilities") },
    { set: "se", qty: "8", name: "Unit reference cards", img: "se-unit-reference.webp", w: 320, h: 177, when: (c) => !c.fote },
    { set: "se", qty: "12", name: "Shock Troop tokens", img: "se-shock-troops.webp", w: 162, h: 159, when: (c) => c.mod("shock") },
    { set: "se", qty: "12", name: "Space Mine tokens", img: "se-space-mines.webp", w: 218, h: 182, when: (c) => c.mod("mines") },
    { set: "se", qty: "2", name: "Mecatol Custodian tokens", img: "se-custodians.webp", w: 318, h: 295, when: (c) => c.mod("custodians") },
    { set: "se", qty: "8", name: "Artifact tokens", note: "4 real, 4 dummies; pictured with their Special Objective cards", img: "se-artifacts.webp", w: 320, h: 99, when: (c) => c.mod("artifacts") },
    { set: "se", qty: "22", name: "Domain counters", note: "New Distant Suns counters", img: "se-domain-counters.webp", w: 320, h: 139, when: (c) => c.mod("newds") },
    { set: "se", qty: "12", name: "Fighter supplement tokens", note: "In 3s — each counts as three Fighters", img: "se-fighter-supplement.webp", w: 154, h: 163, when: (c) => !c.fote },
    { set: "se", qty: "12", name: "Ground Force tokens", note: "Supplement tokens in 3s — each counts as three Ground Forces", img: "se-gf-supplement.webp", w: 154, h: 163, when: (c) => !c.fote },
    { set: "se", qty: "12", name: "Trade Goods", img: "se-trade-goods.webp", w: 175, h: 175, when: (c) => !c.fote },
    { set: "se", qty: "3", name: "Wormhole tokens", note: "For optional map setups published on Fantasy Flight’s website (SE p.6)", img: "se-wormhole-tokens.webp", w: 320, h: 122, when: (c) => !c.fote },

    /* ---- Shards of the Throne (SoT p.5 list) ---- */
    { set: "sot", qty: "16", name: "New system tiles", note: "Includes a Gravity Rift, new Home Systems and the variant Mecatol Rex used only in Fall of the Empire (SoT p.6). 16 in the SoT p.5 contents list; the descriptions on SoT p.6 and p.9 count 14",
      img: "sot-system-tiles.webp", w: 320, h: 169 },
    { set: "sot", qty: "8", name: "Plastic Flagships", note: "One per colour; pictured with the Mechanized Units", img: "sot-plastic-units.webp", w: 320, h: 146, when: (c) => c.mod("flagships") },
    { set: "sot", qty: "32", name: "Plastic Mechanized Units", note: "4 per colour; pictured with the Flagships", img: "sot-plastic-units.webp", w: 320, h: 146, when: (c) => c.mod("mechs") },
    { set: "sot", qty: "4", name: "Race sheets", note: "The three new races and the Lazax (Fall of the Empire only)", img: "sot-race-sheets.webp", w: 320, h: 192 },
    { set: "sot", qty: "64", name: "Command counters", note: "16 for each of the three new races, plus 16 for the Lazax" },
    { set: "sot", qty: "68", name: "Control markers", note: "17 for each of the three new races, plus 17 for the Lazax" },
    { set: "sot", qty: "9", name: "Leader counters", note: "3 for each of the three new races", when: (c) => c.mod("leaders") },
    { set: "sot", qty: "3", name: "Variant Strategy cards", note: "Trade III (Mercenaries), Political II and Assembly II (Political Intrigue); pictured on SoT p.20 (the components page shows only the scenario cards)",
      when: (c) => c.mod("mercs") || c.mod("intrigue") },
    { set: "sot", qty: "2", name: "Scenario Strategy cards", note: "Civilization and Industry, for Fall of the Empire",
      img: "sot-strategy-cards.webp", w: 320, h: 231, when: (c) => c.fote },
    { set: "sot", qty: "34", name: "Action cards", note: "The expansion also provides replacement Ghost Ship and Star of Death cards (SoT p.6)", img: "sot-action-cards.webp", w: 129, h: 193 },
    { set: "sot", qty: "34", name: "Agenda cards", note: "Replace the Political deck in Fall of the Empire (SoT p.14)", img: "sot-agenda-cards.webp", w: 294, h: 212, when: (c) => c.fote },
    { set: "sot", qty: "17", name: "Flagship cards", img: "sot-flagship-cards.webp", w: 294, h: 211, when: (c) => c.mod("flagships") },
    { set: "sot", qty: "1", name: "Lazax Objective card", note: "Pictured with the other new Objective cards", img: "sot-objective-cards.webp", w: 320, h: 173, when: (c) => c.fote },
    { set: "sot", qty: "16", name: "Mercenary cards", img: "sot-mercenary-cards.webp", w: 294, h: 208, when: (c) => c.mod("mercs") },
    { set: "sot", qty: "12", name: "Planet cards", img: "sot-planet-cards.webp", w: 294, h: 212 },
    { set: "sot", qty: "19", name: "Political cards", img: "sot-political-cards.webp", w: 157, h: 211, when: (c) => !c.fote },
    { set: "sot", qty: "40", name: "Promissory Note cards", note: "Five per colour; the grey and orange ones only with Shattered Empire’s plastic (SoT p.6)",
      img: "sot-promissory-notes.webp", w: 294, h: 212, when: (c) => c.mod("intrigue") },
    { set: "sot", qty: "22", name: "Race-specific Technology cards", note: "Cards marked with a red Shattered Empire symbol are used only with both expansions — among them the replacements for Shattered Empire’s Berserker Genome (renamed Valkyrie Armor, FAQ p.12) and Bioptic Recyclers (SoT p.6, p.10)",
      img: "sot-race-techs.webp", w: 294, h: 208, when: (c) => c.mod("rst") },
    { set: "sot", qty: "51", name: "Representative cards", note: "Three per race", img: "sot-representatives.webp", w: 294, h: 209, when: (c) => c.mod("intrigue") },
    { set: "sot", qty: "10", name: "Preliminary Objective cards", note: "Pictured with the other new Objective cards", img: "sot-objective-cards.webp", w: 320, h: 173, when: (c) => c.mod("prelim") },
    { set: "sot", qty: "7", name: "Scenario Objective cards", note: "Replace the Secret Objectives in Fall of the Empire, where no one scores victory points (SoT p.14–15)",
      img: "sot-objective-cards.webp", w: 320, h: 173, when: (c) => c.fote },
    { set: "sot", qty: "32", name: "Technology cards", note: "Four per colour; the grey and orange ones only with Shattered Empire’s plastic (SoT p.8)", img: "sot-technology-cards.webp", w: 294, h: 212 },
    { set: "sot", qty: "8", name: "Trade Contract cards", note: "2 for each of the three new races (SoT p.8), plus the Lazax’s for Fall of the Empire (SoT p.6)" },
    { set: "sot", qty: "31", name: "Treaty cards", img: "sot-treaty-cards.webp", w: 294, h: 212, when: (c) => c.fote },
    { set: "sot", qty: "8", name: "Unit reference cards", img: "sot-unit-reference.webp", w: 294, h: 212 },
    { set: "sot", qty: "15", name: "Space Domain counters", note: "The Final Frontier", img: "sot-space-domain.webp", w: 320, h: 124, when: (c) => c.mod("frontier") },
    { set: "sot", qty: "16", name: "Ground Force supplement counters", note: "In 3s — each counts as three Ground Forces", img: "sot-supplements.webp", w: 294, h: 150 },
    { set: "sot", qty: "16", name: "Fighter supplement counters", note: "In 3s — each counts as three Fighters (only the Ground Force counters are pictured, SoT p.8)" },
    { set: "sot", qty: "16", name: "Mercenary tokens", note: "Two-sided: in space / on a planet, with each side’s battle value", img: "sot-mercenary-tokens.webp", w: 294, h: 187, when: (c) => c.mod("mercs") },
    { set: "sot", qty: "12", name: "Trade Goods counters", note: "In 3s", img: "sot-trade-goods.webp", w: 257, h: 136 },
    { set: "sot", qty: "3", name: "Race-specific Technology tokens", note: "For the Ghosts of Creuss’ and the Embers of Muaat’s special abilities (SoT p.8) — Creuss’ wormhole tokens for its Slave Wormhole Generator and Muaat’s token for its Nova Seed, both Race-Specific Technologies (FAQ p.14)", img: "sot-rst-tokens.webp", w: 288, h: 159, when: (c) => c.mod("rst") }
  ]
};
