/* =============================================================================
   Arkham Horror (2nd Edition) — Components glossary data (standard v1.1; rendered by js/comp-widget.js)
   Sources (printed page numbers; the four small-box rules sheets have none, so their sides are p.1 / p.2):
     Core p.2 (Game Components list) with pictures from the Component Overview, Core p.2–4 ·
     Dunwich p.2 (Components) + Component Overview p.2–3 · Curse p.1 (Game Components + Component Overview) ·
     KiY p.1 · Kingsport p.2 (Components) + Component Overview p.3–4 · Black Goat p.1 ·
     Innsmouth p.2 (Components) + Component Overview p.3–4 · Lurker p.1 · Miskatonic p.1–2 (Component Overview).
   Pictures are cropped from those pages (text removed). Each expansion's rulebook is printed on its own paper,
   so each set's fig is that paper's colour (median crop-corner colour). Counts and names are as each list prints
   them (sentence case); the rulebooks themselves ("This Rulebook") are left out.
   Gating follows the rulebooks:
     - Replacements: Lurker's Gate markers replace the base, Dunwich and Kingsport ones when that variant is on
       (Lurker p.1); Miskatonic's Act cards replace The King in Yellow's (Miskatonic p.2–3).
     - Herald, Guardian, Institution, Epic Battle, Personal Story, Difficulty and Relationship pieces appear only
       with their module; Miskatonic cards for another expansion appear only with that expansion (Miskatonic p.1–3).
   ============================================================================= */
window.AID_COMPONENTS = {
  sets: [
    { id: "base", name: "Arkham Horror (Base Game)", src: "Core p.2–4" },
    { id: "dunwich", name: "The Dunwich Horror", src: "Dunwich p.2–3", fig: "#f4cea6", when: (c) => c.has("dunwich") },
    { id: "curse", name: "Curse of the Dark Pharaoh (Revised)", src: "Curse p.1", fig: "#c5cfd8", when: (c) => c.has("curse") },
    { id: "kingyellow", name: "The King in Yellow", src: "KiY p.1", fig: "#f7f9ed", when: (c) => c.has("kingyellow") },
    { id: "kingsport", name: "Kingsport Horror", src: "Kingsport p.2–4", fig: "#f4cfad", when: (c) => c.has("kingsport") },
    { id: "blackgoat", name: "The Black Goat of the Woods", src: "Black Goat p.1", fig: "#efeeee", when: (c) => c.has("blackgoat") },
    { id: "innsmouth", name: "Innsmouth Horror", src: "Innsmouth p.2–4", fig: "#ddebe1", when: (c) => c.has("innsmouth") },
    { id: "lurker", name: "The Lurker at the Threshold", src: "Lurker p.1", fig: "#f2f1f0", when: (c) => c.has("lurker") },
    { id: "miskatonic", name: "Miskatonic Horror", src: "Miskatonic p.1–2", fig: "#d4e7e1", when: (c) => c.has("miskatonic") }
  ],
  items: [
    /* ---- Arkham Horror (Base Game) ---- */
    { set: "base", qty: "1", name: "Game board", img: "base-board.webp", w: 320, h: 217 },
    { set: "base", qty: "1", name: "First player marker", img: "base-first-player.webp", w: 231, h: 167 },
    { set: "base", qty: "5", name: "Dice", img: "base-dice.webp", w: 167, h: 167 },
    { set: "base", qty: "16", name: "Investigator sheets", img: "base-inv-sheets.webp", w: 234, h: 320 },
    { set: "base", qty: "16", name: "Investigator markers", img: "base-inv-markers.webp", w: 125, h: 118 },
    { set: "base", qty: "16", name: "Plastic investigator stands" },
    { set: "base", qty: "56", name: "Money tokens", img: "base-money.webp", w: 190, h: 218 },
    { set: "base", qty: "34", name: "Sanity tokens", note: "10 “threes” and 24 “ones”", img: "base-sanity.webp", w: 175, h: 106 },
    { set: "base", qty: "34", name: "Stamina tokens", note: "10 “threes” and 24 “ones”", img: "base-stamina.webp", w: 161, h: 126 },
    { set: "base", qty: "48", name: "Clue tokens", img: "base-clues.webp", w: 153, h: 187 },
    { set: "base", qty: "24", name: "Skill sliders", img: "base-skill-sliders.webp", w: 134, h: 148 },
    { set: "base", qty: "44", name: "Common items", img: "base-common-items.webp", w: 140, h: 181 },
    { set: "base", qty: "39", name: "Unique items", img: "base-unique-items.webp", w: 143, h: 181 },
    { set: "base", qty: "40", name: "Spells", img: "base-spells.webp", w: 139, h: 181 },
    { set: "base", qty: "20", name: "Skills", img: "base-skills.webp", w: 141, h: 181 },
    { set: "base", qty: "11", name: "Allies", img: "base-allies.webp", w: 133, h: 181 },
    { set: "base", qty: "8", name: "Retainers", img: "base-retainers.webp", w: 102, h: 162 },
    { set: "base", qty: "8", name: "Silver Twilight Lodge memberships", img: "base-silver-twilight.webp", w: 142, h: 162 },
    { set: "base", qty: "8", name: "Bank loans", img: "base-bank-loans.webp", w: 138, h: 162 },
    { set: "base", qty: "8", name: "Blessing/curse cards", img: "base-blessing-curse.webp", w: 160, h: 162 },
    { set: "base", qty: "3", name: "Deputy cards", img: "base-deputy.webp", w: 145, h: 162 },
    { set: "base", qty: "8", name: "Ancient One sheets", img: "base-ao-sheets.webp", w: 230, h: 320 },
    { set: "base", qty: "20", name: "Doom tokens", note: "Each has an elder sign on the back (Core p.3)", img: "base-doom-tokens.webp", w: 320, h: 148 },
    { set: "base", qty: "63", name: "Location cards", note: "A deck of seven for each of the nine neighborhoods (Core p.3)", img: "base-location-cards.webp", w: 175, h: 200 },
    { set: "base", qty: "67", name: "Mythos cards", img: "base-mythos-cards.webp", w: 195, h: 198 },
    { set: "base", qty: "49", name: "Gate cards", img: "base-gate-cards.webp", w: 190, h: 207 },
    { set: "base", qty: "60", name: "Monster markers", img: "base-monsters.webp", w: 320, h: 168 },
    { set: "base", qty: "16", name: "Gate markers", img: "base-gate-markers.webp", w: 320, h: 177, when: (c) => !c.mod("lurkerGates") },
    { set: "base", qty: "3", name: "Activity markers", img: "base-activity.webp", w: 229, h: 202 },
    { set: "base", qty: "3", name: "Explored markers", img: "base-explored.webp", w: 228, h: 202 },
    { set: "base", qty: "1", name: "Terror track marker", img: "base-terror.webp", w: 109, h: 139 },
    { set: "base", qty: "6", name: "Closed markers", img: "base-closed.webp", w: 109, h: 171 },
    /* ---- The Dunwich Horror ---- */
    { set: "dunwich", qty: "1", name: "Expansion game board", img: "dunwich-board.webp", w: 320, h: 161 },
    { set: "dunwich", qty: "8", name: "Investigator sheets", img: "dunwich-inv-sheets.webp", w: 227, h: 320 },
    { set: "dunwich", qty: "8", name: "Investigator markers", img: "dunwich-inv-markers.webp", w: 120, h: 99 },
    { set: "dunwich", qty: "8", name: "Plastic investigator stands" },
    { set: "dunwich", qty: "24", name: "Injury cards", img: "dunwich-injury.webp", w: 155, h: 152 },
    { set: "dunwich", qty: "24", name: "Madness cards", img: "dunwich-madness.webp", w: 158, h: 154 },
    { set: "dunwich", qty: "15", name: "Common items", note: "Include Tasks, a new type of common item (Dunwich p.2)", img: "dunwich-common-items.webp", w: 148, h: 160 },
    { set: "dunwich", qty: "25", name: "Unique items", note: "Include Missions, a new type of unique item (Dunwich p.2)", img: "dunwich-unique-items.webp", w: 160, h: 160 },
    { set: "dunwich", qty: "21", name: "Spells", img: "dunwich-spells.webp", w: 157, h: 160 },
    { set: "dunwich", qty: "11", name: "Skills", img: "dunwich-skills.webp", w: 155, h: 160 },
    { set: "dunwich", qty: "5", name: "Allies", img: "dunwich-allies.webp", w: 159, h: 160 },
    { set: "dunwich", qty: "8", name: "Sheldon Gang membership cards", img: "dunwich-sheldon-gang.webp", w: 160, h: 150 },
    { set: "dunwich", qty: "8", name: "Rail pass cards", img: "dunwich-rail-pass.webp", w: 151, h: 150 },
    { set: "dunwich", qty: "4", name: "Condition cards", img: "dunwich-conditions.webp", w: 320, h: 71 },
    { set: "dunwich", qty: "7", name: "Replacement Arkham Horror cards", note: "Revised copies of four Flesh Ward (spell), one Healing Stone (unique item) and two Lantern (common item): remove the old copies from the base decks and use these (Dunwich p.2). The revised printing of the base game already has them (FAQ p.1)" },
    { set: "dunwich", qty: "4", name: "Ancient One sheets", img: "dunwich-ao-sheets.webp", w: 234, h: 320 },
    { set: "dunwich", qty: "63", name: "Arkham location cards" },
    { set: "dunwich", qty: "42", name: "Dunwich location cards", note: "Form three new location decks (Dunwich p.3)" },
    { set: "dunwich", qty: "36", name: "Mythos cards", img: "dunwich-mythos-cards.webp", w: 189, h: 203 },
    { set: "dunwich", qty: "32", name: "Gate cards", img: "dunwich-gate-cards.webp", w: 189, h: 194 },
    { set: "dunwich", qty: "7", name: "Dunwich Horror cards", img: "dunwich-dh-cards.webp", w: 263, h: 150 },
    { set: "dunwich", qty: "28", name: "Monster markers", note: "Include one new “Mask” monster and nine Spawn monsters (Dunwich p.3)", img: "dunwich-monsters.webp", w: 290, h: 152 },
    { set: "dunwich", qty: "3", name: "Dunwich Horror tokens", img: "dunwich-dh-tokens.webp", w: 257, h: 173 },
    { set: "dunwich", qty: "4", name: "Gate markers", note: "Show the new Other Worlds, Another Time and Lost Carcosa (Dunwich p.3)", img: "dunwich-gate-markers.webp", w: 320, h: 177, when: (c) => !c.mod("lurkerGates") },
    { set: "dunwich", qty: "7", name: "Rubble markers", note: "Used only when Shudde M’ell is the Ancient One (Dunwich p.3)", img: "dunwich-rubble.webp", w: 276, h: 114 },
    /* ---- Curse of the Dark Pharaoh (Revised) ---- */
    { set: "curse", qty: "22", name: "Exhibit items", img: "curse-exhibit-items.webp", w: 237, h: 205 },
    { set: "curse", qty: "18", name: "Exhibit encounter cards", img: "curse-exhibit-encounters.webp", w: 202, h: 183 },
    { set: "curse", qty: "21", name: "Spells" },
    { set: "curse", qty: "7", name: "Allies" },
    { set: "curse", qty: "4", name: "Benefit cards", note: "Anointed, Private Investigator, Psychic and Visions (Curse p.2)", img: "curse-benefit-detriment.webp", w: 196, h: 200 },
    { set: "curse", qty: "4", name: "Detriment cards", note: "Harried, Local Guide, Tainted and Wanted (Curse p.2)", img: "curse-benefit-detriment.webp", w: 196, h: 200 },
    { set: "curse", qty: "45", name: "Arkham location cards" },
    { set: "curse", qty: "27", name: "Gate cards" },
    { set: "curse", qty: "18", name: "Mythos cards" },
    { set: "curse", qty: "1", name: "Dark Pharaoh herald sheet", img: "curse-herald.webp", w: 277, h: 186, when: (c) => c.mod("heraldPharaoh") },
    { set: "curse", qty: "1", name: "Ancient Whispers marker", img: "curse-whispers.webp", w: 192, h: 190 },
    { set: "curse", qty: "9", name: "Patrol markers", img: "curse-patrol.webp", w: 209, h: 202 },
    /* ---- The King in Yellow ---- */
    { set: "kingyellow", qty: "19", name: "Common item cards" },
    { set: "kingyellow", qty: "22", name: "Unique item cards" },
    { set: "kingyellow", qty: "15", name: "Spell cards" },
    { set: "kingyellow", qty: "13", name: "Blight cards", img: "kingyellow-blight.webp", w: 208, h: 195, when: (c) => c.mod("heraldKiY") },
    { set: "kingyellow", qty: "7", name: "Magical effect cards", img: "kingyellow-magical-effects.webp", w: 130, h: 193 },
    { set: "kingyellow", qty: "36", name: "Arkham location cards" },
    { set: "kingyellow", qty: "24", name: "Gate cards" },
    { set: "kingyellow", qty: "27", name: "Mythos cards" },
    { set: "kingyellow", qty: "3", name: "Act cards", img: "kingyellow-act.webp", w: 267, h: 179, when: (c) => !c.has("miskatonic") },
    { set: "kingyellow", qty: "1", name: "Herald sheet (The King in Yellow)", img: "kingyellow-herald.webp", w: 283, h: 177, when: (c) => c.mod("heraldKiY") },
    { set: "kingyellow", qty: "10", name: "Yellow sign tokens", img: "kingyellow-yellow-sign.webp", w: 165, h: 166, when: (c) => c.mod("heraldKiY") },
    { set: "kingyellow", qty: "3", name: "Riot monster markers", note: "Spawn monsters (KiY p.1)", img: "kingyellow-riots.webp", w: 282, h: 228, when: (c) => c.mod("heraldKiY") },
    /* ---- Kingsport Horror ---- */
    { set: "kingsport", qty: "1", name: "Expansion game board", img: "kingsport-board.webp", w: 320, h: 171 },
    { set: "kingsport", qty: "8", name: "Investigator sheets", img: "kingsport-inv-sheets.webp", w: 268, h: 320 },
    { set: "kingsport", qty: "8", name: "Investigator markers", img: "kingsport-inv-markers.webp", w: 132, h: 157 },
    { set: "kingsport", qty: "8", name: "Plastic investigator stands" },
    { set: "kingsport", qty: "3", name: "Guardian sheets", img: "kingsport-guardian-sheets.webp", w: 320, h: 224, when: (c) => c.mod("guardianNodens") || c.mod("guardianHypnos") || c.mod("guardianBast") },
    { set: "kingsport", qty: "14", name: "Common items" },
    { set: "kingsport", qty: "12", name: "Unique items" },
    { set: "kingsport", qty: "11", name: "Spells" },
    { set: "kingsport", qty: "12", name: "Skills" },
    { set: "kingsport", qty: "11", name: "Allies" },
    { set: "kingsport", qty: "20", name: "Blessings of Nodens cards", img: "kingsport-nodens.webp", w: 299, h: 285, when: (c) => c.mod("guardianNodens") },
    { set: "kingsport", qty: "26", name: "Visions of Hypnos cards", img: "kingsport-hypnos.webp", w: 292, h: 283, when: (c) => c.mod("guardianHypnos") },
    { set: "kingsport", qty: "2", name: "Beloved of Bast cards", img: "kingsport-beloved-bast.webp", w: 297, h: 289, when: (c) => c.mod("guardianBast") },
    { set: "kingsport", qty: "2", name: "Captain of the White Ship cards", note: "Gained at the North Point Lighthouse (Kingsport p.3)", img: "kingsport-captain.webp", w: 286, h: 289 },
    { set: "kingsport", qty: "2", name: "Changed cards", note: "Gained at the Strange High House in the Mists (Kingsport p.3)", img: "kingsport-changed.webp", w: 273, h: 293 },
    { set: "kingsport", qty: "4", name: "Ancient One sheets", img: "kingsport-ao-sheets.webp", w: 252, h: 320 },
    { set: "kingsport", qty: "2", name: "Herald sheets", img: "kingsport-herald-sheets.webp", w: 320, h: 210, when: (c) => c.mod("heraldGhroth") || c.mod("heraldTulzscha") },
    { set: "kingsport", qty: "36", name: "Arkham location cards" },
    { set: "kingsport", qty: "56", name: "Kingsport location cards", note: "Form four new location decks (Kingsport p.4)", img: "kingsport-location-cards.webp", w: 320, h: 217 },
    { set: "kingsport", qty: "22", name: "Mythos cards" },
    { set: "kingsport", qty: "32", name: "Gate cards" },
    { set: "kingsport", qty: "16", name: "Epic Battle cards", note: "Eight green and eight red (Kingsport p.11)", img: "kingsport-epic.webp", w: 320, h: 223, when: (c) => c.mod("epicBattle") },
    { set: "kingsport", qty: "45", name: "Ancient One plot cards", note: "The three that show this game’s Ancient One are set aside for the Epic Battle (Kingsport p.11)", when: (c) => c.mod("epicBattle") },
    { set: "kingsport", qty: "28", name: "Monster markers", note: "Include two new “Mask” monsters (Kingsport p.4)", img: "kingsport-monsters.webp", w: 320, h: 198 },
    { set: "kingsport", qty: "3", name: "Rift markers", img: "kingsport-rift-markers.webp", w: 320, h: 245 },
    { set: "kingsport", qty: "12", name: "Rift progress markers", img: "kingsport-rift-progress.webp", w: 277, h: 186 },
    { set: "kingsport", qty: "4", name: "Gate markers", note: "Show the new Other Worlds, the Underworld and Unknown Kadath (Kingsport p.4)", img: "kingsport-gate-markers.webp", w: 320, h: 205, when: (c) => !c.mod("lurkerGates") },
    { set: "kingsport", qty: "48", name: "Brood tokens", note: "Used only when Eihort is the Ancient One (Kingsport p.4)", img: "kingsport-brood.webp", w: 235, h: 229 },
    { set: "kingsport", qty: "8", name: "Bast tokens", img: "kingsport-bast-tokens.webp", w: 250, h: 221, when: (c) => c.mod("guardianBast") },
    { set: "kingsport", qty: "2", name: "Aquatic markers", note: "Mark the River Docks and the Unvisited Isle as aquatic locations (Kingsport p.4)", img: "kingsport-aquatic.webp", w: 224, h: 252 },
    { set: "kingsport", qty: "1", name: "Skill slider", note: "A fourth slider for Lily Chen, the Martial Artist (Kingsport p.4)", img: "kingsport-skill-slider.webp", w: 191, h: 151 },
    /* ---- The Black Goat of the Woods ---- */
    { set: "blackgoat", qty: "11", name: "Common item cards" },
    { set: "blackgoat", qty: "11", name: "Unique item cards" },
    { set: "blackgoat", qty: "4", name: "Spell cards" },
    { set: "blackgoat", qty: "8", name: "“One of the Thousand” cult membership cards", img: "blackgoat-cult-membership.webp", w: 194, h: 288 },
    { set: "blackgoat", qty: "16", name: "Green corruption cards", img: "blackgoat-green-corruption.webp", w: 194, h: 290 },
    { set: "blackgoat", qty: "16", name: "Red corruption cards", img: "blackgoat-red-corruption.webp", w: 195, h: 288 },
    { set: "blackgoat", qty: "24", name: "Cult encounter cards", img: "blackgoat-cult-encounters.webp", w: 194, h: 288 },
    { set: "blackgoat", qty: "36", name: "Arkham location cards" },
    { set: "blackgoat", qty: "24", name: "Gate cards" },
    { set: "blackgoat", qty: "23", name: "Mythos cards" },
    { set: "blackgoat", qty: "5", name: "Difficulty cards", note: "Two easier, two harder and one normal (Black Goat p.2)", when: (c) => c.mod("difficulty") },
    { set: "blackgoat", qty: "1", name: "Herald sheet (The Black Goat of the Woods)", when: (c) => c.mod("heraldBlackGoat") },
    { set: "blackgoat", qty: "9", name: "Monster markers", note: "All have the hexagon dimensional symbol (Black Goat p.1)" },
    /* ---- Innsmouth Horror ---- */
    { set: "innsmouth", qty: "1", name: "Expansion game board", img: "innsmouth-board.webp", w: 320, h: 171 },
    { set: "innsmouth", qty: "16", name: "Investigator sheets", img: "innsmouth-inv-sheets.webp", w: 320, h: 293 },
    { set: "innsmouth", qty: "16", name: "Investigator markers", img: "innsmouth-inv-markers.webp", w: 261, h: 187 },
    { set: "innsmouth", qty: "16", name: "Plastic investigator stands" },
    { set: "innsmouth", qty: "96", name: "Personal stories", note: "Two for every investigator, including those from Arkham, Dunwich and Kingsport Horror (Innsmouth p.3, p.10)", img: "innsmouth-personal-stories.webp", w: 320, h: 264, when: (c) => c.mod("personalStories") },
    { set: "innsmouth", qty: "8", name: "Ancient One sheets", img: "innsmouth-ao-sheets.webp", w: 246, h: 320 },
    { set: "innsmouth", qty: "36", name: "Arkham location cards" },
    { set: "innsmouth", qty: "42", name: "Innsmouth location cards", note: "Form three new location decks (Innsmouth p.3)", img: "innsmouth-location-cards.webp", w: 320, h: 217 },
    { set: "innsmouth", qty: "36", name: "Mythos cards" },
    { set: "innsmouth", qty: "16", name: "Gate cards" },
    { set: "innsmouth", qty: "24", name: "Ancient One plot cards", note: "For Kingsport Horror’s Epic Battle variant (Innsmouth p.3)", img: "innsmouth-plot.webp", w: 320, h: 226, when: (c) => c.mod("epicBattle") },
    { set: "innsmouth", qty: "10", name: "Innsmouth Look cards", img: "innsmouth-look.webp", w: 320, h: 248 },
    { set: "innsmouth", qty: "12", name: "Small dust cards", note: "Used only when Quachil Uttaus is the Ancient One (Innsmouth p.3)", img: "innsmouth-dust.webp", w: 320, h: 208 },
    { set: "innsmouth", qty: "2", name: "Herald sheets", img: "innsmouth-herald-sheets.webp", w: 320, h: 208, when: (c) => c.mod("heraldDagon") || c.mod("heraldHydra") },
    { set: "innsmouth", qty: "32", name: "Monster markers", note: "Include two new “Mask” monsters and five new Spawn monsters (Innsmouth p.4)", img: "innsmouth-monsters.webp", w: 320, h: 199 },
    { set: "innsmouth", qty: "6", name: "Uprising tokens", img: "innsmouth-uprising.webp", w: 258, h: 243 },
    { set: "innsmouth", qty: "8", name: "Ghatanothoa’s visage tokens", note: "Used only when Ghatanothoa is the Ancient One (Innsmouth p.4)", img: "innsmouth-visage.webp", w: 320, h: 216 },
    { set: "innsmouth", qty: "1", name: "Zhar token", note: "Used only in the final battle when Zhar is the Ancient One (Innsmouth p.4)", img: "innsmouth-zhar.webp", w: 320, h: 230 },
    { set: "innsmouth", qty: "2", name: "Aquatic markers", note: "Identical to the two in Kingsport Horror: they mark the River Docks and the Unvisited Isle (Innsmouth p.4)", img: "innsmouth-aquatic.webp", w: 224, h: 252 },
    /* ---- The Lurker at the Threshold ---- */
    { set: "lurker", qty: "4", name: "Common item cards" },
    { set: "lurker", qty: "4", name: "Unique items cards" },
    { set: "lurker", qty: "12", name: "Spell cards" },
    { set: "lurker", qty: "12", name: "Relationship cards", note: "Used only in games with two or more players (Lurker p.1)", img: "lurker-relationships.webp", w: 213, h: 162, when: (c) => c.has("lurker") && c.p >= 2 && !c.mod("noRelationships") },
    { set: "lurker", qty: "24", name: "Dark pact cards", note: "8 Blood Pact, 8 Soul Pact and 8 Bound Ally cards (Lurker p.1)", img: "lurker-dark-pacts.webp", w: 316, h: 160, when: (c) => c.mod("heraldLurker") },
    { set: "lurker", qty: "36", name: "Arkham location cards" },
    { set: "lurker", qty: "24", name: "Gate cards" },
    { set: "lurker", qty: "22", name: "Mythos cards" },
    { set: "lurker", qty: "28", name: "Reckoning cards", img: "lurker-reckoning.webp", w: 209, h: 160, when: (c) => c.mod("heraldLurker") },
    { set: "lurker", qty: "1", name: "Herald sheet (The Lurker at the Threshold)", when: (c) => c.mod("heraldLurker") },
    { set: "lurker", qty: "18", name: "Gate markers", note: "Replace the Gate markers of the base game, Dunwich and Kingsport. Without Dunwich, leave out the three to Another Time or Lost Carcosa; without Kingsport, the three to Unknown Kadath or Underworld (Lurker p.1)", img: "lurker-gate-markers.webp", w: 185, h: 185, when: (c) => c.mod("lurkerGates") },
    { set: "lurker", qty: "35", name: "Power tokens", img: "lurker-power.webp", w: 92, h: 93, when: (c) => c.mod("heraldLurker") },
    /* ---- Miskatonic Horror ---- */
    { set: "miskatonic", qty: "7", name: "Skill cards", note: "Each relates to another expansion; return any whose expansion isn’t in play (Miskatonic p.1, p.3)", img: "miskatonic-skills.webp", w: 177, h: 159 },
    { set: "miskatonic", qty: "9", name: "Exhibit encounter cards", img: "miskatonic-exhibit-encounters.webp", w: 177, h: 159, when: (c) => c.has("curse") },
    { set: "miskatonic", qty: "5", name: "Exhibit items", img: "miskatonic-exhibit-items.webp", w: 177, h: 159, when: (c) => c.has("curse") },
    { set: "miskatonic", qty: "12", name: "Injuries cards", img: "miskatonic-injuries.webp", w: 177, h: 159, when: (c) => c.has("dunwich") },
    { set: "miskatonic", qty: "12", name: "Madness cards", img: "miskatonic-madness.webp", w: 177, h: 159, when: (c) => c.has("dunwich") },
    { set: "miskatonic", qty: "7", name: "Blight cards", note: "Only when The King in Yellow is the Herald and an expansion board is in play (Miskatonic p.1)", img: "miskatonic-blight.webp", w: 177, h: 159, when: (c) => c.mod("heraldKiY") && (c.has("dunwich") || c.has("kingsport") || c.has("innsmouth")) },
    { set: "miskatonic", qty: "6", name: "Blessings of Nodens cards", img: "miskatonic-nodens.webp", w: 177, h: 159, when: (c) => c.mod("guardianNodens") },
    { set: "miskatonic", qty: "16", name: "Visions of Hypnos cards", img: "miskatonic-hypnos.webp", w: 177, h: 158, when: (c) => c.mod("guardianHypnos") },
    { set: "miskatonic", qty: "24", name: "Cult encounter cards", img: "miskatonic-cult-encounters.webp", w: 177, h: 159, when: (c) => c.has("blackgoat") },
    { set: "miskatonic", qty: "6", name: "Relationship cards", img: "miskatonic-relationships.webp", w: 177, h: 159, when: (c) => c.has("lurker") && c.p >= 2 && !c.mod("noRelationships") },
    { set: "miskatonic", qty: "8", name: "Miskatonic Student cards", note: "Later flipped to the “Miskatonic Alumnus” side (Miskatonic p.1)", img: "miskatonic-student.webp", w: 177, h: 159, when: (c) => c.mod("instMisk") },
    { set: "miskatonic", qty: "56", name: "Gate cards", note: "Expansion icons show which expansions each card needs (Miskatonic p.1)", img: "miskatonic-gate-cards.webp", w: 226, h: 203 },
    { set: "miskatonic", qty: "43", name: "Mythos cards", img: "miskatonic-mythos-cards.webp", w: 226, h: 202 },
    { set: "miskatonic", qty: "60", name: "Dunwich location cards", img: "miskatonic-dunwich-locations.webp", w: 226, h: 202, when: (c) => c.has("dunwich") },
    { set: "miskatonic", qty: "6", name: "Dunwich Horror cards", img: "miskatonic-dh-cards.webp", w: 216, h: 154, when: (c) => c.has("dunwich") },
    { set: "miskatonic", qty: "4", name: "Act cards", note: "Used in place of The King in Yellow’s Act cards (Miskatonic p.2–3)", img: "miskatonic-act.webp", w: 219, h: 156, when: (c) => c.has("kingyellow") },
    { set: "miskatonic", qty: "80", name: "Kingsport location cards", img: "miskatonic-kingsport-locations.webp", w: 226, h: 202, when: (c) => c.has("kingsport") },
    { set: "miskatonic", qty: "8", name: "Epic Battle cards", note: "Add Battle Conditions and Battle Events (Miskatonic p.2)", img: "miskatonic-epic.webp", w: 226, h: 240, when: (c) => c.mod("epicBattle") },
    { set: "miskatonic", qty: "60", name: "Innsmouth location cards", img: "miskatonic-innsmouth-locations.webp", w: 226, h: 202, when: (c) => c.has("innsmouth") },
    { set: "miskatonic", qty: "5", name: "Innsmouth Look cards", img: "miskatonic-look.webp", w: 226, h: 202, when: (c) => c.has("innsmouth") },
    { set: "miskatonic", qty: "14", name: "Reckoning cards", img: "miskatonic-reckoning.webp", w: 226, h: 203, when: (c) => c.mod("heraldLurker") },
    { set: "miskatonic", qty: "1", name: "Dunwich Horror herald sheet", img: "miskatonic-dh-herald.webp", w: 320, h: 207, when: (c) => c.mod("heraldDunwich") },
    { set: "miskatonic", qty: "3", name: "Institution sheets", img: "miskatonic-institutions.webp", w: 320, h: 207, when: (c) => c.mod("instMisk") || c.mod("instBureau") || c.mod("instOrgCrime") },
    { set: "miskatonic", qty: "4", name: "Player reference sheets", img: "miskatonic-player-refs.webp", w: 320, h: 207 },
    { set: "miskatonic", qty: "38", name: "Agent tokens", img: "miskatonic-agents.webp", w: 97, h: 97, when: (c) => c.mod("instBureau") },
    { set: "miskatonic", qty: "3", name: "Expedition markers", img: "miskatonic-expedition.webp", w: 145, h: 114, when: (c) => c.mod("instMisk") }
  ]
};
